config/routes.rb
Rails.application.routes.draw do
  root 'users# new'
  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :picture_blogs do
    collection do
    post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture_blog.rb
class PictureBlog < ApplicationRecord
  belongs_to :user
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_picture_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/picture_blogs_controller.rb
class PictureBlogsController < ApplicationController
  before_action :set_picture_blog, only: [:show, :edit, :update, :destroy]
  def index
    @picture_blogs = PictureBlog.all
  end

  def new
    @picture_blog = PictureBlog.new
  end

  def create
    @picture_blog = PictureBlog.new(blog_params)
    if params[:back]
      render :new
    end
    if redirect_to picture_blogs_path, notice: '投稿を作成しました！！'
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
    if @picture_blog.update(picture_blog_params)
      redirect_to picture_blogs_path, notice: "投稿を編集しました！！"
    else
      render :new
    end
  end

  def destroy
    @picture_blog.destroy
    redirect_to picture_blogs_path, notice:"投稿を削除しました！！"
  end

  def confirm
    @picture_blog = PictureBlog.new(picture_blog_params)
    render :new if @picture_blog.invalid?
  end

end

private

def picture_blog_params
  params.require(:picture_blog).permit(:title, :content)
end

def set_picture_blog
  @picture_blog = PictureBlog.find(params[:id])
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picture_blogs_helper.rb
module PictureBlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      picture_blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FbClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "Profile", user_path(current_user.id) %>
      <%= link_to "Logout", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/picture_blogs/_form.html.erb
<%= form_with(model: @picture_blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @picture_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @picture_blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @picture_blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="picture_blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="picture_blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>
<%= link_to "ブログ一覧画面にもどる", picture_blogs_path %>

app/views/picture_blogs/confirm.html.erb
<h3>以下の内容で、投稿する。</h3>
<%= form_with(model: @picture_blog, url: picture_blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content, value: current_user.id  %>
  <p>タイトル:<%= @picture_blog.title %></p>
  <p>本文:<%= @picture_blog.content %></p>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back' %>
<% end %>

app/views/picture_blogs/edit.html.erb
<h1>PictureBlogs#edit</h1>
<p>Find me in app/views/picture_blogs/edit.html.erb</p>

app/views/picture_blogs/index.html.erb
<h1>PictureBlogs#index</h1>
<p>Find me in app/views/picture_blogs/index.html.erb</p>

app/views/picture_blogs/new.html.erb
<h1>PictureBlogs#new</h1>
<p>Find me in app/views/picture_blogs/new.html.erb</p>

app/views/picture_blogs/show.html.erb
<h1>PictureBlogs#show</h1>
<p>Find me in app/views/picture_blogs/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>